"""hello

Revision ID: db8913e6917e
Revises: be1bd8d88d40
Create Date: 2024-01-14 15:06:36.987127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8913e6917e'
down_revision = 'be1bd8d88d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
